[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prcwatermark"
version = "0.0.1"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["prcwatermark"] 
